development:
  event_api_base_path: "http://juicer.responsivenews.co.uk/api/events/"
  event_base_path: "http://juicer.responsivenews.co.uk/events/"

  rdf_base_path: "http://127.0.0.1:5001/rdf?identifier="
  article_base_path: "http://127.0.0.1:5001/articles/"
  people_base_path: "http://127.0.0.1:5001/people/"
  places_base_path: "http://127.0.0.1:5001/places/"
  events_base_path: "http://127.0.0.1:5001/events/"

  article_query_base_uri: "http://juicer.responsivenews.co.uk/api/articles?"
  article_query_json_path: "http://juicer.responsivenews.co.uk/articles?"
test:
  event_api_base_path: "http://127.0.0.1:6666/api/events/"
  event_base_path: "http://juicer.responsivenews.co.uk/events/"
  rdf_base_path: "http://127.0.0.1:6666/rdf?identifier="
  article_base_path: "http://bbc-blender.herokuapp.com/articles/"

  article_query_base_uri: "http://juicer.responsivenews.co.uk/api/articles?"
  article_query_json_path: "http://juicer.responsivenews.co.uk/articles?"
production:
  event_api_base_path: "http://juicer.responsivenews.co.uk/api/events/"
  event_base_path: "http://juicer.responsivenews.co.uk/events/"

  rdf_base_path: "http://bbc-blender.herokuapp.com/rdf?identifier="
  article_base_path: "http://bbc-blender.herokuapp.com/articles/"
  people_base_path: "http://bbc-blender.herokuapp.com/people/"
  places_base_path: "http://bbc-blender.herokuapp.com/places/"
  events_base_path: "http://bbc-blender.herokuapp.com/events/"

  article_query_base_uri: "http://juicer.responsivenews.co.uk/api/articles?"
  article_query_json_path: "http://juicer.responsivenews.co.uk/articles?"
