paths:
  "/api/events/1" : 
    file_location : "spec/data/event.json"
    content-type: "application/json"
  "/rdf?identifier=http://dbpedia.org/resource/resource_name" : 
    file_location : "spec/data/resource.xml"
    content-type: "application/rdf+xml"
