paths:
  "/api/events/1" : 
    file_location : "rest-assured/data/event.json"
    content-type: "application/json"
  "/rdf?identifier=http://dbpedia.org/resource/person_resource_name" : 
    file_location : "rest-assured/data/person_resource.xml"
    content-type: "application/rdf+xml"
  "/rdf?identifier=http://dbpedia.org/resource/place_resource_name" : 
    file_location : "rest-assured/data/place_resource.xml"
    content-type: "application/rdf+xml"
  "/rdf?identifier=http://juicer.responsivenews.co.uk/events/1" : 
    file_location : "rest-assured/data/event_resource.xml"
    content-type: "application/rdf+xml"
  "/rdf?identifier=http://www.bbc.co.uk/news/article-1234" : 
    file_location : "rest-assured/data/article_resource.xml"
    content-type: "application/rdf+xml"
  "/api/articles?binding=article&limit=5&where=?article%20%3Chttp://data.press.net/ontology/tag/mentions%3E%20%3Chttp://dbpedia.org/resource/person_resource_name%3E" : 
    file_location : "rest-assured/data/article_person_query.json"
    content-type: "application/json"

